### ISSUE TITLE
Can you provide a download link in release, so we can add it to CPL?

### ISSUE THREAD

**Issue by linonetwo** [EvidentlyCube/TW5-AdvancedPerformance#2]
Like describe in https://github.com/felixhayashi/TW5-TiddlyMap/issues/430 , thanks!

**Comment by linonetwo** [comment]
Also I'd like to add this plugin to [https://github.com/tiddly-gittly/TiddlyWiki-TS-Plugin-Template](https://github.com/tiddly-gittly/TiddlyWiki-TS-Plugin-Template) , so I need a JSON file from the release.

**Comment by EvidentlyCube** [comment]
@linonetwo  The plugins are now available in a library (though not yet announced or mentioned):
* Library Tiddler: https://evidentlycube.github.io/TW5-PluginShowcase/#Evidently%20Cube%20Plugin%20Library
* Library HTML: https://evidentlycube.github.io/TW5-PluginShowcase/library.html
* Library JSON: https://evidentlycube.github.io/TW5-PluginShowcase/recipes/library/tiddlers.json
* Advanced Performance plugin permalink: https://evidentlycube.github.io/TW5-PluginShowcase/recipes/library/tiddlers/%2524%253A%252Fplugins%252FEvidentlyCube%252FAdvancedPerformance.json

I have no plans to change any of those URLs (with the exception of name of the library tiddler), will those suffice?

Also keep in mind that Advanced Pirformance just running in the background with performance instrumentation enabled slows things down a bit. Not by a huge margin, very likely less than 20%, but it's not something you want constantly enabled.

**Comment by EvidentlyCube** [comment]
The library is now officially available here: https://evidentlycube.github.io/TW5-PluginShowcase/#Plugin%20Library

The remaining URLs from the previous comment are still valid - I am closing this ticket since I believe that should suffice.
